name: Build Edge

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "10 4 * * */2"

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [head]
        mode: ['auto', 'patch']
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      REQUIRE_HOOKS_MODE: ${{ matrix.mode }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run MSpec
      run: bundle exec bin/mspec
