name: TruffleRuby Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  truffle-test-require-hooks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_PATH: /home/runner/bundle
      TRUFFLERUBYOPT: "--engine.Mode=latency"
      CI: true
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby-head
        bundler-cache: true
    - name: Run MSpec
      run: bundle exec bin/mspec
